In [2]:
import numpy as np
import pickle as pkl

In [9]:
with open('/home/zhangkechi/workspace/riddle/clone_detection/code/run_bert-base-chinese_chaizi/1654258646.0284004eval_vecs.pkl','rb') as f:
    tmp1 = pkl.load(f)

In [35]:
tmp1['ans_vecs']

array([[ 0.61617655,  0.9566449 ,  0.4093911 , ...,  0.84309316,
         0.82807654,  0.83613914],
       [ 0.61617655,  0.9566449 ,  0.4093911 , ...,  0.84309316,
         0.82807654,  0.83613914],
       [ 0.61617655,  0.9566449 ,  0.4093911 , ...,  0.84309316,
         0.82807654,  0.83613914],
       ...,
       [-0.73211217,  0.9412314 , -0.05126529, ...,  0.6225742 ,
         0.64847994,  0.8871019 ],
       [-0.73211217,  0.9412314 , -0.05126529, ...,  0.6225742 ,
         0.64847994,  0.8871019 ],
       [-0.73211217,  0.9412314 , -0.05126529, ...,  0.6225742 ,
         0.64847994,  0.8871019 ]], dtype=float32)

In [11]:
with open('/home/zhangkechi/workspace/riddle/clone_detection/code/run_bert-base-chinese_chaizi/1654257807.839481eval_vecs.pkl','rb') as f:
    tmp2 = pkl.load(f)

In [23]:
tmp2['ans_vecs']

array([[0.39570338, 0.9611537 , 0.31179762, ..., 0.7290586 , 0.48481485,
        0.737254  ],
       [0.9020382 , 0.97373337, 0.8028132 , ..., 0.80344886, 0.89876974,
        0.9250159 ],
       [0.22699386, 0.96734786, 0.09420803, ..., 0.65801525, 0.84540176,
        0.6648083 ],
       ...,
       [0.46464223, 0.9951129 , 0.75417125, ..., 0.9212722 , 0.8449898 ,
        0.9666675 ],
       [0.46464223, 0.9951129 , 0.75417125, ..., 0.9212722 , 0.8449898 ,
        0.9666675 ],
       [0.46464223, 0.9951129 , 0.75417125, ..., 0.9212722 , 0.8449898 ,
        0.9666675 ]], dtype=float32)

In [31]:
for i in range(len(tmp1['ans_vecs'])):
    for j in range(i):
        if np.linalg.norm(tmp1['ans_vecs'][i]-tmp1['ans_vecs'][j])<1e-5:
            print(i,j)

1 0
2 0
2 1
3 0
3 1
3 2
5 4
6 4
6 5
7 4
7 5
7 6
8 4
8 5
8 6
8 7
9 4
9 5
9 6
9 7
9 8
10 4
10 5
10 6
10 7
10 8
10 9
11 4
11 5
11 6
11 7
11 8
11 9
11 10
14 13
15 13
15 14
16 13
16 14
16 15
18 17
19 17
19 18
20 17
20 18
20 19
21 17
21 18
21 19
21 20
22 17
22 18
22 19
22 20
22 21
23 17
23 18
23 19
23 20
23 21
23 22
24 17
24 18
24 19
24 20
24 21
24 22
24 23
25 17
25 18
25 19
25 20
25 21
25 22
25 23
25 24
26 17
26 18
26 19
26 20
26 21
26 22
26 23
26 24
26 25
27 17
27 18
27 19
27 20
27 21
27 22
27 23
27 24
27 25
27 26
28 17
28 18
28 19
28 20
28 21
28 22
28 23
28 24
28 25
28 26
28 27
29 17
29 18
29 19
29 20
29 21
29 22
29 23
29 24
29 25
29 26
29 27
29 28
31 30
32 30
32 31
33 30
33 31
33 32
34 30
34 31
34 32
34 33
35 30
35 31
35 32
35 33
35 34
36 30
36 31
36 32
36 33
36 34
36 35
37 30
37 31
37 32
37 33
37 34
37 35
37 36
38 30
38 31
38 32
38 33
38 34
38 35
38 36
38 37
39 30
39 31
39 32
39 33
39 34
39 35
39 36
39 37
39 38
40 30
40 31
40 32
40 33
40 34
40 35
40 36
40 37
40 38
40 39
41 30
41 31
41 3

KeyboardInterrupt: 

array([ 6.16176546e-01,  9.56644893e-01,  4.09391105e-01, -9.37499762e-01,
        5.82551241e-01,  7.72886157e-01,  9.84960020e-01,  2.60613382e-01,
        5.75694561e-01, -1.04118824e-01,  2.00129613e-01,  4.35887985e-02,
       -1.96319625e-01, -3.74042362e-01, -8.35906029e-01,  4.91930068e-01,
       -9.67237353e-01, -9.85954583e-01,  7.20959902e-01, -1.68005731e-02,
       -5.43968320e-01,  9.69087362e-01, -6.61746948e-04,  1.34257395e-02,
        5.12400046e-02, -8.08117628e-01, -9.55641866e-01, -9.49956954e-01,
       -2.32162923e-01, -3.04405428e-02, -7.08117247e-01,  9.08155832e-03,
        6.97314367e-02, -2.52391219e-01, -1.45498052e-01, -5.11057258e-01,
       -8.68613303e-01, -9.63521481e-01, -9.62722182e-01, -3.95976186e-01,
       -9.20300305e-01, -9.66168404e-01,  9.34450626e-01, -9.55412447e-01,
        9.88019824e-01,  3.29446107e-01,  9.75774646e-01,  5.98720729e-01,
        4.85115349e-01,  6.41904831e-01,  9.47563648e-01, -3.18418473e-01,
       -4.91844952e-01, -